services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      
 
volumes:
  pgdata: