"""aa

Revision ID: 41762cbc89ad
Revises: a812abf6623e
Create Date: 2025-02-22 22:07:25.662902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41762cbc89ad'
down_revision: Union[str, None] = 'a812abf6623e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'todo_list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'todo_list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
