"""Add TodoList and Task tables

Revision ID: 8c452cef6d70
Revises: 217b7d67e219
Create Date: 2025-02-22 21:39:47.906941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c452cef6d70'
down_revision: Union[str, None] = '217b7d67e219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
