"""aa

Revision ID: dcb2a8dc46f7
Revises: 24e6251e01b8
Create Date: 2025-02-22 21:59:37.779610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb2a8dc46f7'
down_revision: Union[str, None] = '24e6251e01b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_lists', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('todo_lists', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_lists', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todo_lists', 'title')
    # ### end Alembic commands ###
